### ISSUE TITLE
Error when using multiple GPUs for training

### ISSUE THREAD

**Issue by MU-MU-M** [Algolzw/image-restoration-sde#90]
Hi,
I got a trouble when training the model by multiple GPUs.
The error message is "**[E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=219996, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1805148 milliseconds before timing out.**"
This error message popped out when storing the training state checkpoint because the iteration reach the save_checkpoint_freq I've set.
How can I sovle this problem of distributed training.

![image](https://github.com/Algolzw/image-restoration-sde/assets/72603727/4bf4458b-cfc8-4eed-8c90-16e70e5f26ee)
![image](https://github.com/Algolzw/image-restoration-sde/assets/72603727/5d52fa79-e662-4896-8c84-67538ed54a97)

Thanks.

**Comment by Algolzw** [comment]
Hi! I haven't met this problem before. What task are you running and has the checkpoint been successfully stored?

**Comment by MU-MU-M** [comment]
I was running the deblurring task. There are indeed some checkpoints can be saved successfully, but fail at a certain iteration (10000'th iteration).

**Comment by MU-MU-M** [comment]
The issue has been resolved. It appears that my disk experienced a malfunction.
